added a sanitize_filename method
kitovu-bot/kitovu pull request #20
Opened 2018-05-03 07:16 UTC by ThunderKey

2018-05-03 08:28 UTC, The-Compiler requested changes
This will break things, because `syncing.py` tries then to ask for the filenames the plugin returned, and those don't actually exist on the server.

Instead, `syncing.py` should probably only sanitize the output filename, no?

2018-05-03 09:37 UTC, ThunderKey commented
Oh yeah...

The problem would be Folders with slashes in them. This would lead to sub folders, which could be confusing. E.g. "17./18. of March"

2018-05-03 09:41 UTC, ThunderKey commented
But I guess it's the best option. The only alternative I'd see would be a "translation" dictionary, which would make everything much more complicated

2018-05-07 19:42 UTC, The-Compiler requested changes

2018-05-07 19:42 UTC, The-Compiler commented on src/kitovu/sync/syncing.py
> +                utils.sanitize_filename(str(remote_full_path.relative_to(remote_dir)))
I'd prefer to add a second variable to break this, e.g.

```python
filename: str = utils.sanitize_filename(str(remote_full_path.relative_to(remote_dir)))
local_full_path: pathlib.Path = local_dir / filename
```

2018-05-07 19:42 UTC, The-Compiler commented on src/kitovu/utils.py
> +def sanitize_filename(name: str, replacement: typing.Optional[str] = '_') -> str:
Might be more in line with what we do elsewhere to take a `pathlib.PurePath` (and return one) here instead.

2018-05-07 19:42 UTC, The-Compiler commented on src/kitovu/utils.py
> +    """
Probably okay to drop at least the `Args:` part of the docstring here.

2018-05-07 19:42 UTC, The-Compiler commented on src/kitovu/utils.py
> +        replacement = ''
We don't need this for kitovu, so let's remove it. Actually, we don't need the ability to customize the replacement char at all.

2018-05-07 19:42 UTC, The-Compiler commented on tests/test_utils.py
> +class TestSanitizeFilename():
Drop the `()` for consistency with other classes.

2018-05-07 19:42 UTC, The-Compiler commented on tests/test_utils.py
> +import pytest
Also see https://github.com/qutebrowser/qutebrowser/blob/v1.3.0/tests/unit/utils/test_utils.py#L632-L638 for my tests, but I think yours are fine as well.

2018-05-08 09:15 UTC, The-Compiler approved these changes

2018-05-08 09:15 UTC, merged

2018-05-08 09:20 UTC, The-Compiler commented
I opened [EPJ-94](https://jira.keltec.ch/jira/browse/EPJ-94) for how to handle slashes in filenames. Like you say, it'd be nice to handle this in a nicer way.