Add basic logging support
kitovu-bot/kitovu pull request #25
Opened 2018-05-08 05:57 UTC by The-Compiler

See EPJ-74

```
$ kitovu sync                                                           
Syncing connection moodle
Syncing subject VSS

Syncing connection skripte-server
Syncing subject Engineering-Projekt
Downloading Informatik/Fachbereich/Engineering-Projekt/EPJ/FS2018/Projektantraege/Projektantrag_kitovu.pdf
```

```
$ kitovu --loglevel debug sync
[...]
2018-05-08 07:57:16,823 [DEBUG]       kitovu.sync.syncing Checking: Informatik/Fachbereich/Engineering-Projekt/EPJ/FS2018/Projektantraege/projektantrag_hiddencomment.pdf
2018-05-08 07:57:16,827 [DEBUG]       kitovu.sync.syncing Remote digest: 597226-1519720070
2018-05-08 07:57:16,827 [DEBUG]     kitovu.sync.filecache Discovering changes for local: /home/florian/proj/kitovu/synctest/Engineering-Projekt/FS2018/Projektantraege/projektantrag_hiddencomment.pdf / remote: Informatik/Fachbereich/Engineering-Projekt/EPJ/FS2018/Projektantraege/projektantrag_hiddencomment.pdf by plugin smb
2018-05-08 07:57:16,831 [DEBUG]     kitovu.sync.filecache Comparing digests: remote 597226-1519720070, local 597226-1519720070, cached 597226-1519720070
2018-05-08 07:57:16,832 [DEBUG]       kitovu.sync.syncing No remote changes.
2018-05-08 07:57:16,832 [DEBUG]       kitovu.sync.syncing Checking: Informatik/Fachbereich/Engineering-Projekt/EPJ/FS2018/Projektantraege/Projektantrag_kitovu.pdf
2018-05-08 07:57:16,836 [DEBUG]       kitovu.sync.syncing Remote digest: 67550-1519719998
2018-05-08 07:57:16,837 [DEBUG]     kitovu.sync.filecache Discovering changes for local: /home/florian/proj/kitovu/synctest/Engineering-Projekt/FS2018/Projektantraege/Projektantrag_kitovu.pdf / remote: Informatik/Fachbereich/Engineering-Projekt/EPJ/FS2018/Projektantraege/Projektantrag_kitovu.pdf by plugin smb
2018-05-08 07:57:16,837 [DEBUG]     kitovu.sync.filecache Local path does not exist!
2018-05-08 07:57:16,837 [INFO]       kitovu.sync.syncing Downloading Informatik/Fachbereich/Engineering-Projekt/EPJ/FS2018/Projektantraege/Projektantrag_kitovu.pdf
2018-05-08 07:57:16,838 [DEBUG]    kitovu.sync.plugin.smb Retrieving file Informatik/Fachbereich/Engineering-Projekt/EPJ/FS2018/Projektantraege/Projektantrag_kitovu.pdf
2018-05-08 07:57:16,851 [DEBUG]       kitovu.sync.syncing Local digest: 67550-1519719998
2018-05-08 07:57:16,851 [DEBUG]     kitovu.sync.filecache Modifying cached digest for /home/florian/proj/kitovu/synctest/Engineering-Projekt/FS2018/Projektantraege/Projektantrag_kitovu.pdf by <kitovu.sync.plugin.smb.SmbPlugin object at 0x7fc464abefd0>: 67550-1519719998
[...]
```

2018-05-08 19:06 UTC, ThunderKey requested changes

2018-05-08 19:06 UTC, ThunderKey commented on src/kitovu/cli.py
> +    logging.getLogger('SMB.SMBConnection').propagate = False
Wouldn't the SMB-Plugin be a better place for this? I'd expect only the SMB-Plugin to know anything about this

2018-05-09 13:24 UTC, The-Compiler commented on src/kitovu/cli.py
> +    logging.getLogger('SMB.SMBConnection').propagate = False
Good point. I moved it there, and also added a `debug` option in the config to turn it back on easily.

2018-05-09 13:38 UTC, ThunderKey approved these changes

2018-05-09 14:10 UTC, merged