User Documentation, New Cli-command.
kitovu-bot/kitovu pull request #31
Opened 2018-05-08 14:10 UTC by bytinbit

Please look at docs/usage.rst, syncing.py and cli.py where I've added the code. The rest of the files have been added as "new" out of unknown reasons.

The cli-command returns the location of the config file and the file path, since this differs from OS to OS. However, I had to add a helper method to show the path to the FileCache - please check if that's ok.

2018-05-09 13:34 UTC, The-Compiler requested changes

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +Du kannst kitovu sowohl mit einer grafischen Oberfläche verwenden als auch über die Kommandozeile. Bevor du kitovu verwenden kannst, musst du jedoch die Konfigurationsdatei erstellen, siehe weiter un
Komma vor "als auch"?

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +    * ``kitovu gui`` startet die grafische Oberfläche
Punkte am Ende damits konsistent ist?

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +    * ``kitovu fileinfo`` sagt dir, wo kitovu zwei wichtige Dateien speichert, die Konfigurationsdatei und der FileCache.
speichert, -> speichert: (also Doppelpunkt statt Komma) würde IMHO besser passen.

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +    * ``kitovu edit`` öffnet die Konfigurationsdatei in einem Editor. Dieser kann mit ``--editor [EDITOR_NAME]`` oder über die Umgebungsvariable ``EDITOR`` angegeben werden. Ansonsten versucht er gän
"versucht er" - wer ist "er"? (und Komma nach "er"?)

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +    Dateien die sich zwischen zwei Synchronisationszeitpunkten geändert haben - etwa, weil du sie selber bearbeitet hast -, werden beim derzeitigen Entwicklungsstandpunkt von kitovu überschrieben.
`-,` macht glaubs wenig Sinn?

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +Es sind keine Leerzeichen in Namen erlaubt. Möchtest du Leerzeichen verwenden, etwa für ``name``, musst du es in Gänsefüsschen setzen: ``Betriebssysteme2`` oder ``"Betriebssysteme 2"``.
"musst du es" - was ist "es"? Ev. "den Wert" stattdessen?

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +``plugin``: Der Name der Plattform, der kitovu intern verwendet, damit eine Verbindung zustande kommt. Derzeit gibt es die fixe Bezeichnungen ``smb`` oder ``moodle``.
die fixe**n**

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +``username``: Dein Login-Name, womit du dich auch andernorts an der Schule einloggst, bestehend aus Vor- und Nachname. Moodle verlangt keinen Usernamen, dafür nach einem Sicherheitsschlüssel (s. weit
Das impliziert, dass man hier den Schlüssel angeben soll - das stimmt aber nicht.

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +``subjects`` bezeichnet ein Unterrichtsmodul, das du an der Schule belegst, beispielsweise "Betriebssysteme 1" oder "Objektorientierte Programmierung in Java".
nicht ein Modul, sondern mehree, oder?

2018-05-09 13:34 UTC, The-Compiler commented on docs/usage.rst
> +Wenn du Dateien synchronisierst, hält kitovu das in einem Log fest. Nach Ende eines Semesters bzw. nach Prüfungsende kannst du diese Datei wieder löschen - also wenn keines der Unterrichtsmodule des
"Log" klingt hier IMHO immer noch seltsam (und wird von nicht-Informatikstudenten wohl kaum verstanden in dem Kontext).

2018-05-10 19:25 UTC, bytinbit commented on docs/usage.rst
> +Du kannst kitovu sowohl mit einer grafischen Oberfläche verwenden als auch über die Kommandozeile. Bevor du kitovu verwenden kannst, musst du jedoch die Konfigurationsdatei erstellen, siehe weiter un
No comma.

2018-05-10 19:27 UTC, bytinbit commented on docs/usage.rst
> +    Dateien die sich zwischen zwei Synchronisationszeitpunkten geändert haben - etwa, weil du sie selber bearbeitet hast -, werden beim derzeitigen Entwicklungsstandpunkt von kitovu überschrieben.
neugeschrieben

2018-05-10 19:28 UTC, bytinbit commented on docs/usage.rst
> +Es sind keine Leerzeichen in Namen erlaubt. Möchtest du Leerzeichen verwenden, etwa für ``name``, musst du es in Gänsefüsschen setzen: ``Betriebssysteme2`` oder ``"Betriebssysteme 2"``.
angepasst, "es" bezieht sich eigentlich auf "Name", ist aber ein Fehlbezug.

2018-05-13 12:29 UTC, The-Compiler approved these changes

2018-05-13 12:30 UTC, merged